# Generated by Django 5.2.17 on 2026-10-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dermal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPMHandbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('principles', '8 Nguyên tắc canh tác'), ('inspection', '7 Bước kiểm tra đồng ruộng'), ('ipm', '10 Bước IPM (FAO)'), ('safe', 'An toàn BVTV & 4 Đúng')], max_length=20)),
                ('step_num', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['section', 'step_num'],
            },
        ),
        migrations.CreateModel(
            name='TomatoDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_vi', models.CharField(max_length=150)),
                ('pathogen', models.CharField(help_text='Tác nhân gây bệnh (nấm / vi khuẩn)', max_length=200)),
                ('color', models.CharField(default='#ea580c', help_text='Màu nhận diện bounding box', max_length=20)),
                ('severity_default', models.CharField(default='Nghiêm trọng', max_length=50)),
                ('confidence_default', models.FloatField(default=50.0)),
                ('symptoms_stage1', models.TextField(blank=True, default='', help_text='Giai đoạn 1: Khởi phát')),
                ('symptoms_stage2', models.TextField(blank=True, default='', help_text='Giai đoạn 2: Phát triển')),
                ('symptoms_stage3', models.TextField(blank=True, default='', help_text='Giai đoạn 3: Bùng phát')),
                ('conditions', models.TextField(blank=True, default='', help_text='Điều kiện nhiệt ẩm thuận lợi phát sinh')),
                ('prevention', models.TextField(blank=True, default='', help_text='Cách phòng ngừa canh tác')),
                ('treatment_cultural', models.TextField(blank=True, default='', help_text='1. Biện pháp canh tác')),
                ('treatment_bio', models.TextField(blank=True, default='', help_text='2. Biện pháp sinh học')),
                ('treatment_chemical', models.TextField(blank=True, default='', help_text='3. Biện pháp hóa học (4 đúng)')),
                ('references', models.TextField(blank=True, default='', help_text='Nguồn tài liệu khoa học FAO, IRRI, v.v.')),
            ],
        ),
        migrations.AlterModelOptions(
            name='leaf_image',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Độ tin cậy %'),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='detections',
            field=models.JSONField(blank=True, default=list, help_text='Tọa độ bounding boxes [x, y, w, h]'),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='is_coinfection',
            field=models.BooleanField(default=False, help_text='Cảnh báo phát hiện đa bệnh (đồng nhiễm)'),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='model_version',
            field=models.CharField(default='v3', help_text="Mô hình sử dụng: 'v3' hoặc 'v4'", max_length=20),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='plant_type',
            field=models.CharField(default='tomato', help_text='Loại cây: Cà chua (tomato)', max_length=50),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='primary_disease',
            field=models.CharField(blank=True, default='', help_text='Mã bệnh chính', max_length=100),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='primary_disease_vi',
            field=models.CharField(blank=True, default='', help_text='Tên tiếng Việt', max_length=150),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='secondary_diseases',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách bệnh phụ phát hiện'),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='severity',
            field=models.CharField(default='Nghiêm trọng', help_text='Mức độ nghiêm trọng', max_length=50),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='supabase_id',
            field=models.CharField(blank=True, default='', help_text='ID bản ghi trên Supabase', max_length=100),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='synced_to_supabase',
            field=models.BooleanField(default=False, help_text='Trạng thái đồng bộ Supabase Cloud'),
        ),
        migrations.AddField(
            model_name='leaf_image',
            name='treatment_summary',
            field=models.TextField(blank=True, default='', help_text='Tóm tắt phác đồ điều trị 3 cấp độ'),
        ),
        migrations.AlterField(
            model_name='leaf_image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dermal.profile'),
        ),
    ]
