# Generated by Django 6.1.1 on 2026-10-02 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaf_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Leaf_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('heatmap', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('more', models.TextField(blank=True, default='')),
                ('explain', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('age', models.CharField(blank=True, default='', max_length=10)),
                ('symptom', models.TextField(blank=True, default='')),
                ('illness_history', models.TextField(blank=True, default='')),
                ('drug_history', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dermal.profile')),
            ],
        ),
    ]
